### ISSUE TITLE
Building the plugin for UE 5.3 throws multiple errors

### ISSUE THREAD

**Issue by RazaZaidi2802** [MrDrElliot/Multi-Window-Plugin#2]
I'm trying to build the plugin to use with UE 5.3. I've created an empty 5.3 C++ project, added the plugin to its Plugins folder and then launched the VS project and tried to build. I've used this method multiple times in the past to re-compile plugins to both, upgrade and downgrade engine versions.

![image](https://github.com/user-attachments/assets/c267d3e9-d5ae-4034-96cb-80749a5789cf)

I think the major error in this is the implicit conversion from ObjectType to bool.

Any way to fix this? I don't have much knowledge in C++

**Comment by MrDrElliot** [comment]
Hi I'm sorry, I haven't even touched this plugin in a long time. I didn't realize anyone was using it. Let me take a look.

**Comment by RazaZaidi2802** [comment]
Thank you! I'll wait. God bless!

**Comment by MrDrElliot** [comment]
Okay, should be all fixed. I also changed some code so you no longer have to get the subsystem for no reason, and you can just use the static functions.

![image](https://github.com/user-attachments/assets/40c1d389-357b-4f79-8063-1303f90ede9c)

Let me know if you have any issues @RazaZaidi2802

**Comment by RazaZaidi2802** [comment]
Thank you! Checking, will update you in a bit

**Comment by MrDrElliot** [comment]
I'm going to make another change, one moment.

**Comment by RazaZaidi2802** [comment]
Got it, I'll wait

**Comment by MrDrElliot** [comment]
![image](https://github.com/user-attachments/assets/a67de5c1-c35d-46d6-b664-13d36763f5e6)

There you go, now you can just give it a widget class. And I also made the nodes a little fancier :) 

@RazaZaidi2802

**Comment by RazaZaidi2802** [comment]
Thank you! I was setting up a quick viewport with a render target for this. I'll import the latest version of the plugin and get back to you asap with results

**Comment by MrDrElliot** [comment]
Oops, had to fix something again 📦

**Comment by RazaZaidi2802** [comment]
![image](https://github.com/user-attachments/assets/d5041973-d034-4073-a6aa-2843c196e61e)
 
The previous build also works great! I'll download the latest version too. Thank you! You're the best!

**Comment by RazaZaidi2802** [comment]
Quick question, is there any chance to be able to have the primary and secondary windows automatically dock side by side like how we can dock Windows 10 Windows?
